### ISSUE TITLE
file absent

### ISSUE THREAD

**Issue by Jiawei0o0** [HUANGLIZI/ScribbleVC#1]
Thanks for your awesome project.
I can't find a file in this project. Could you please upload it?
"catagory_list = pd.read_excel('../data/ACDC/slice_classification.xlsx'"

**Comment by HUANGLIZI** [comment]
Hi, sorry for the inconveniences. The files have been uploaded. Hope it can address your concern.

**Comment by Jiawei0o0** [comment]
And the "--pretrain_weights cnnTransformer.pth " is required. Or maybe it doesn't actually matter?
