### ISSUE TITLE
MSCMR dataset

### ISSUE THREAD

**Issue by Jiawei0o0** [HUANGLIZI/ScribbleVC#2]
Hi, sorry to bother you.
Could you upload the detail code about how to load the MSCMR dataset? I can't find "/MSCMR_training_slices" and "/MSCMR_training_volumes" followed the dataset link provided in the readme.md. 
By the way, it will be grateful if you can fulfill the code test_MSCMR.  
Thanks a lot.

**Comment by HUANGLIZI** [comment]
Thanks for your attention on our work. You can find the training slice on the file slice_classification_MSCMR.xlsx(https://github.com/HUANGLIZI/ScribbleVC/blob/main/slice_classification_MSCMR.xlsx)

**Comment by Jiawei0o0** [comment]
I can't fetch the “.h5” file in (https://github.com/BWGZK/CycleMix/tree/main/MSCMR_dataset).
Can you provide it ?

**Comment by Jiawei0o0** [comment]
Thanks for your reply. I have fixed it.
