### ISSUE TITLE
"Pretrain_weights" parameter file

### ISSUE THREAD

**Issue by Gardnery** [HUANGLIZI/ScribbleVC#3]
Hello, I am interested in the "pretrain_weights" parameter in the project
There are some doubts about the source of the "cnnTransformer. pth" file. I would like to inquire if this file was previously trained or downloaded from elsewhere?

**Comment by HUANGLIZI** [comment]
Yes, you can train it from the previous pretrain model or from scratch. And unfortunately, our pretrain model is not available now.
