### ISSUE TITLE
The details of the h5 file of acdc dataset with scribble labeled. 

### ISSUE THREAD

**Issue by Carmen279252** [HUANGLIZI/ScribbleVC#5]
Hello, there is no h5 file of scribble in the related dataset link you gave. I think your code reads h5 file, but the scribble file of acdc data set is in nii.gz format. How did you convert the scribble image in nii.gz format into h5 file, so that it is convenient for me to give your related processing code or the h5 data of scribble image?

**Comment by HUANGLIZI** [comment]
you can refer to the repo https://github.com/HiLab-git/WSL4MIS to get the h5 data.
